eureka:
  instance:
    hostname: spring-gateway-server
  client:
    service-url:
      defaultZone: http://spring-discovery-server:8080/eureka
    register-with-eureka: false
spring:
  cloud:
    gateway:
      routes:
        - id: locks
          uri: http://spring-lock-server:8080
          predicates:
            - Path=/api/v1/locks/**
        - id: users
          uri: http://spring-user-server:8080
          predicates:
            - Path=/api/v1/users/**
        - id: messages
          uri: http://spring-message-server:8080
          predicates:
            - Path=/api/v1/messages/**
        - id: logs
          uri: http://spring-logging-server:8080
          predicates:
            - Path=/api/v1/logs/**
        - id: files
          uri: http://spring-static-server:80
          predicates:
            - Path=/api/v1/files/**
            - Path=/files/**
