eureka:
  instance:
    hostname: spring-gateway-server
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: false

spring:
  cloud:
    gateway:
      routes:
        - id: locks
          uri: http://localhost:8300
          predicates:
            - Path=/api/v1/locks/**
        - id: users
          uri: http://localhost:8100
          predicates:
            - Path=/api/v1/users/**
        - id: messages
          uri: http://localhost:8200
          predicates:
            - Path=/api/v1/messages/**
        - id: logs
          uri: http://localhost:8700
          predicates:
            - Path=/api/v1/logs/**
        - id: files
          uri: http://localhost:8500
          predicates:
            - Path=/api/v1/files/**
            - Path=/files/**